apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-nginx-config
  namespace: todo-app
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        server {
            listen 80;
            server_name localhost;
            root /usr/share/nginx/html;
            index index.html;

            # Enable gzip compression
            gzip on;
            gzip_vary on;
            gzip_min_length 1024;
            gzip_proxied any;
            gzip_comp_level 6;
            gzip_types
                application/javascript
                application/json
                application/xml
                text/css
                text/javascript
                text/plain
                text/xml;

            # Handle client-side routing
            location / {
                try_files $uri $uri/ /index.html;
            }

            # Cache static assets
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
            }
        }
    }