name: Auto Merge Pull Request

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened, ready_for_review]
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
  status: {}

env:
  MERGE_METHOD: squash
  BRANCHES_ALLOWED: main,develop

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.draft == false &&
      contains(env.BRANCHES_ALLOWED, github.event.pull_request.base.ref)
    
    steps:
    - name: Auto-merge Pull Request
      uses: pascalgn/merge-action@v0.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        merge-method: ${{ env.MERGE_METHOD }}
        merge-filter-author: ""
        merge-labels: "auto-merge"
        merge-forks: false
        merge-commit-message: |
          Auto-merge: #{issue.title} (#{issue.number})
          
          {issue.body}
        merge-remove-branch: true
        merge-retries: "3"
        merge-retry-sleep: "10000"

    - name: Check if PR is mergeable
      id: check-mergeable
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          
          // Check if PR is mergeable
          if (pr.mergeable && pr.mergeable_state === 'clean') {
            console.log('PR is mergeable');
            return true;
          } else {
            console.log('PR is not mergeable. State:', pr.mergeable_state);
            return false;
          }
        result-encoding: string

    - name: Add merge label if conditions met
      if: steps.check-mergeable.outputs.result == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: ['auto-merge']
          });