name: Reusable Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      k8s-namespace:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-files
        path: dist

    - name: Set up Kubeconfig
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Verify Kubernetes cluster
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        # Update image in deployment
        kubectl set image deployment/todo-app todo-app=${{ inputs.image }} -n ${{ inputs.k8s-namespace }} --record
        
        # Wait for rollout to complete
        kubectl rollout status deployment/todo-app -n ${{ inputs.k8s-namespace }} --timeout=300s

    - name: Verify deployment
      run: |
        kubectl get pods -n ${{ inputs.k8s-namespace }}
        kubectl get services -n ${{ inputs.k8s-namespace }}
        kubectl get ingress -n ${{ inputs.k8s-namespace }}