name: Main CI/CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

permissions:
  contents: read
  packages: write
jobs:
  # 1️⃣ Test & Build
  test-build:
    uses: ./.github/workflows/reusable-test-build.yml

  # 2️⃣ Security Scan
  security-scan:
    uses: ./.github/workflows/run-security-scan.yml

  # 3️⃣ Docker Build & Push
  docker-build-push:
    needs: [test-build, security-scan]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/docker-push.yml
    secrets: inherit
    with:
      registry: docker.io
      image-name: akta2910/todo-app



  # 6️⃣ Auto-merge PRs
  trigger-auto-merge:
    needs: [test-build, security-scan]
    if: github.event_name == 'pull_request' && always() && !contains(needs.*.conclusion, 'failure') && !contains(needs.*.conclusion, 'cancelled')
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge check
        run: echo "All checks passed - PR can be auto-merged"