name: Reusable Security Scan

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Snyk token exists
        run: |
          if [ -z "${SNYK_TOKEN}" ]; then
            echo "❌ SNYK_TOKEN is empty! Make sure it is added in repo secrets."
            exit 1
          else
            echo "✅ SNYK_TOKEN is set correctly."
          fi

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
