name: Run Security Scan

on:
  push:
    branches: [ master ]

jobs:
  call-security-scan:
    uses: ./.github/workflows/reusable-security-scan.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
